{% set name = "python-ghostscript" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/pdftools/python-ghostscript/-/archive/v{{ version }}/{{ name }}-v{{ version }}.tar.bz2
  sha256: c718262002a68b3ea0b8b685a950fee6c4da82ef7e2def2e28dc0f2a58f912bf
  patches:
    # hardcode dllpath on windows
    - windll_path.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - ghostscript
    - python >=3.6
    - pip
  run:
    - ghostscript
    - python >=3.6
    - setuptools

test:
  imports:
    - ghostscript
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/pdftools/python-ghostscript
  summary: Interface to the Ghostscript C-API, both high- and low-level, based on ctypes
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - akrherz
